import { Cast, Scheme } from '../models';

function reps(low: number, high: number, label?: string): Scheme {
  return {
    kind: 'reps',
    low,
    high,
    label: label ?? (low === high ? `${low} reps` : `${low}-${high} reps`),
  };
}

function time(low: number, high: number, unit: 's' | 'min', label?: string): Scheme {
  return {
    kind: 'time',
    low,
    high,
    unit,
    label:
      label ??
      (low === high
        ? `${low}${unit === 's' ? 's' : ' min'}`
        : `${low}-${high}${unit === 's' ? 's' : ' min'}`),
  };
}

/**
 * The full cast library (GDD section 5). Content-as-data per GDD 20.3 —
 * new casts/seasons can extend this array without touching the Arena UI.
 * "X or Y" tool alternatives are modelled as two casts sharing a swap_group
 * so the resolver's normal candidate filter (tools ⊆ player.tools) picks
 * whichever the player actually owns.
 */
export const CASTS: Cast[] = [
  // 5.1 Squat
  {
    id: 'sit_to_stand',
    name: 'Sit to Stand',
    rune_id: 'squat',
    rank: 1,
    place_tags: ['home', 'gym'],
    tools_required: ['floor'],
    joint_blockers: [],
    cues: ['Chest tall, drive through your heels.'],
    default_scheme: reps(8, 10),
    swap_group: 'squat',
  },
  {
    id: 'box_squat',
    name: 'Box Squat',
    rune_id: 'squat',
    rank: 2,
    place_tags: ['home', 'gym'],
    tools_required: ['floor'],
    joint_blockers: ['knees'],
    cues: ['Tap the box lightly, stand tall.'],
    default_scheme: reps(8, 8),
    swap_group: 'squat',
  },
  {
    id: 'goblet_squat_db',
    name: 'Goblet Squat',
    rune_id: 'squat',
    rank: 3,
    place_tags: ['home', 'gym'],
    tools_required: ['dumbbells'],
    joint_blockers: ['knees'],
    cues: ['Elbows inside your knees at the bottom.'],
    default_scheme: reps(8, 8),
    swap_group: 'goblet_squat',
  },
  {
    id: 'goblet_squat_pack',
    name: 'Goblet Squat',
    rune_id: 'squat',
    rank: 3,
    place_tags: ['home', 'gym'],
    tools_required: ['backpack'],
    joint_blockers: ['knees'],
    cues: ['Elbows inside your knees at the bottom.'],
    default_scheme: reps(8, 8),
    swap_group: 'goblet_squat',
  },
  {
    id: 'leg_press',
    name: 'Leg Press',
    rune_id: 'squat',
    rank: 3,
    place_tags: ['gym'],
    tools_required: ['machines'],
    joint_blockers: [],
    cues: ['Full range, no lockout slam.'],
    default_scheme: reps(10, 10),
    swap_group: 'squat',
  },

  // 5.2 Hinge
  {
    id: 'chair_hinge',
    name: 'Chair Hinge',
    rune_id: 'hinge',
    rank: 1,
    place_tags: ['home', 'gym'],
    tools_required: ['floor'],
    joint_blockers: ['back'],
    cues: ['Hips back, shallow and controlled.'],
    default_scheme: reps(8, 8),
    swap_group: 'hinge',
  },
  {
    id: 'backpack_rdl',
    name: 'Backpack RDL',
    rune_id: 'hinge',
    rank: 2,
    place_tags: ['home'],
    tools_required: ['backpack'],
    joint_blockers: ['back'],
    cues: ['Flat back, hips drive the movement.'],
    default_scheme: reps(8, 8),
    swap_group: 'hinge',
  },
  {
    id: 'db_rdl',
    name: 'Dumbbell RDL',
    rune_id: 'hinge',
    rank: 3,
    place_tags: ['home', 'gym'],
    tools_required: ['dumbbells'],
    joint_blockers: ['back'],
    cues: ['Bar/weight close to the legs.'],
    default_scheme: reps(8, 8),
    swap_group: 'hinge',
  },
  {
    id: 'hip_thrust_floor',
    name: 'Hip Thrust',
    rune_id: 'hinge',
    rank: 2,
    place_tags: ['home', 'gym'],
    tools_required: ['floor'],
    joint_blockers: [],
    cues: ['Squeeze at the top, ribs down.'],
    default_scheme: reps(8, 8),
    swap_group: 'hinge',
  },
  {
    id: 'cable_rdl',
    name: 'Cable RDL',
    rune_id: 'hinge',
    rank: 3,
    place_tags: ['gym'],
    tools_required: ['machines'],
    joint_blockers: [],
    cues: ['Slow eccentric, hips lead.'],
    default_scheme: reps(8, 8),
    swap_group: 'hinge',
  },

  // 5.3 Press
  {
    id: 'wall_pushup',
    name: 'Wall Push-up',
    rune_id: 'press',
    rank: 1,
    place_tags: ['home', 'gym'],
    tools_required: ['floor'],
    joint_blockers: ['wrists'],
    cues: ['Straight line, elbows at 45 degrees.'],
    default_scheme: reps(8, 8),
    swap_group: 'press',
  },
  {
    id: 'knee_pushup',
    name: 'Knee Push-up',
    rune_id: 'press',
    rank: 2,
    place_tags: ['home', 'gym'],
    tools_required: ['floor'],
    joint_blockers: ['shoulders', 'wrists'],
    cues: ['Hips level with shoulders, no sag.'],
    default_scheme: reps(6, 8),
    swap_group: 'press',
  },
  {
    id: 'pushup',
    name: 'Push-up',
    rune_id: 'press',
    rank: 3,
    place_tags: ['home', 'gym'],
    tools_required: ['floor'],
    joint_blockers: ['shoulders'],
    cues: ['Full lockout, ribs braced.'],
    default_scheme: reps(5, 8),
    swap_group: 'press',
  },
  {
    id: 'chest_press_machine',
    name: 'Chest Press Machine',
    rune_id: 'press',
    rank: 2,
    place_tags: ['gym'],
    tools_required: ['machines'],
    joint_blockers: [],
    cues: ['Smooth press, no bounce off the stack.'],
    default_scheme: reps(8, 8),
    swap_group: 'press',
  },
  {
    id: 'db_floor_press',
    name: 'DB Floor Press',
    rune_id: 'press',
    rank: 2,
    place_tags: ['home', 'gym'],
    tools_required: ['dumbbells'],
    joint_blockers: [],
    cues: ['Upper arms tap the floor, press up.'],
    default_scheme: reps(8, 8),
    swap_group: 'press',
  },

  // 5.4 Overhead
  {
    id: 'seated_bag_press',
    name: 'Seated Bag Press',
    rune_id: 'overhead',
    rank: 1,
    place_tags: ['home'],
    tools_required: ['backpack'],
    joint_blockers: ['shoulders'],
    cues: ['Ribs down, press straight up.'],
    default_scheme: reps(8, 8),
    swap_group: 'overhead',
  },
  {
    id: 'db_seated_press',
    name: 'DB Seated Press',
    rune_id: 'overhead',
    rank: 2,
    place_tags: ['home', 'gym'],
    tools_required: ['dumbbells'],
    joint_blockers: ['shoulders'],
    cues: ['Back supported, press to lockout.'],
    default_scheme: reps(6, 8),
    swap_group: 'overhead',
  },
  {
    id: 'machine_ohp',
    name: 'Machine Overhead Press',
    rune_id: 'overhead',
    rank: 2,
    place_tags: ['gym'],
    tools_required: ['machines'],
    joint_blockers: [],
    cues: ['Full range, controlled tempo.'],
    default_scheme: reps(8, 8),
    swap_group: 'overhead',
  },
  {
    id: 'db_stand_press',
    name: 'DB Standing Press',
    rune_id: 'overhead',
    rank: 3,
    place_tags: ['home', 'gym'],
    tools_required: ['dumbbells'],
    joint_blockers: ['shoulders', 'back'],
    cues: ['Brace hard, avoid leaning back.'],
    default_scheme: reps(6, 6),
    swap_group: 'overhead',
  },

  // 5.5 Pull
  {
    id: 'table_row',
    name: 'Table Row',
    rune_id: 'pull',
    rank: 1,
    place_tags: ['home'],
    tools_required: ['floor'],
    joint_blockers: [],
    cues: ['Squeeze shoulder blades together.'],
    default_scheme: reps(8, 8),
    swap_group: 'pull',
  },
  {
    id: 'backpack_row',
    name: 'Backpack Row',
    rune_id: 'pull',
    rank: 1,
    place_tags: ['home'],
    tools_required: ['backpack'],
    joint_blockers: [],
    cues: ['Elbow drives back, not out.'],
    default_scheme: reps(8, 8),
    swap_group: 'pull',
  },
  {
    id: 'band_row',
    name: 'Band Row',
    rune_id: 'pull',
    rank: 2,
    place_tags: ['home', 'gym'],
    tools_required: ['bands'],
    joint_blockers: [],
    cues: ['Steady tension, no jerking.'],
    default_scheme: reps(10, 10),
    swap_group: 'pull',
  },
  {
    id: 'db_row',
    name: 'DB Row',
    rune_id: 'pull',
    rank: 3,
    place_tags: ['home', 'gym'],
    tools_required: ['dumbbells'],
    joint_blockers: ['back'],
    cues: ['Flat back, pull to the hip.'],
    default_scheme: reps(8, 8),
    swap_group: 'pull',
  },
  {
    id: 'seated_row_machine',
    name: 'Seated Row Machine',
    rune_id: 'pull',
    rank: 2,
    place_tags: ['gym'],
    tools_required: ['machines'],
    joint_blockers: [],
    cues: ['Chest tall, squeeze at the finish.'],
    default_scheme: reps(10, 10),
    swap_group: 'pull',
  },

  // 5.6 Climb
  {
    id: 'dead_hang',
    name: 'Dead Hang',
    rune_id: 'climb',
    rank: 1,
    place_tags: ['home', 'gym'],
    tools_required: ['pullup_bar'],
    joint_blockers: ['wrists', 'shoulders'],
    cues: ['Relax the shoulders, breathe.'],
    default_scheme: time(20, 20, 's'),
    swap_group: 'climb',
  },
  {
    id: 'scap_pull_bar',
    name: 'Scap Pull',
    rune_id: 'climb',
    rank: 1,
    place_tags: ['home', 'gym'],
    tools_required: ['pullup_bar'],
    joint_blockers: [],
    cues: ['Shoulder blades down and together.'],
    default_scheme: reps(6, 6),
    swap_group: 'scap_pull',
  },
  {
    id: 'scap_pull_band',
    name: 'Scap Pull',
    rune_id: 'climb',
    rank: 1,
    place_tags: ['home', 'gym'],
    tools_required: ['bands'],
    joint_blockers: [],
    cues: ['Shoulder blades down and together.'],
    default_scheme: reps(6, 6),
    swap_group: 'scap_pull',
  },
  {
    id: 'band_assist_pulldown',
    name: 'Band Assisted Pulldown',
    rune_id: 'climb',
    rank: 2,
    place_tags: ['home', 'gym'],
    tools_required: ['bands'],
    joint_blockers: [],
    cues: ['Pull elbows to your ribs.'],
    default_scheme: reps(8, 8),
    swap_group: 'climb',
  },
  {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    rune_id: 'climb',
    rank: 2,
    place_tags: ['gym'],
    tools_required: ['machines'],
    joint_blockers: [],
    cues: ['Lead with the elbows, no swing.'],
    default_scheme: reps(8, 8),
    swap_group: 'climb',
  },
  {
    id: 'pullup',
    name: 'Pull-up',
    rune_id: 'climb',
    rank: 3,
    place_tags: ['home', 'gym'],
    tools_required: ['pullup_bar'],
    joint_blockers: [],
    cues: ['Chin over the bar, control the drop.'],
    default_scheme: reps(3, 6),
    swap_group: 'climb',
  },

  // 5.7 Brace
  {
    id: 'dead_bug',
    name: 'Dead Bug',
    rune_id: 'brace',
    rank: 1,
    place_tags: ['home', 'gym'],
    tools_required: ['floor'],
    joint_blockers: ['back'],
    cues: ['Low back stays flat on the floor.'],
    default_scheme: reps(6, 6, '6/side'),
    swap_group: 'brace',
  },
  {
    id: 'plank',
    name: 'Plank',
    rune_id: 'brace',
    rank: 2,
    place_tags: ['home', 'gym'],
    tools_required: ['floor'],
    joint_blockers: ['wrists'],
    cues: ['Straight line, ribs pulled down.'],
    default_scheme: time(20, 30, 's'),
    swap_group: 'brace',
  },
  {
    id: 'suitcase_hold_db',
    name: 'Suitcase Hold',
    rune_id: 'brace',
    rank: 2,
    place_tags: ['home', 'gym'],
    tools_required: ['dumbbells'],
    joint_blockers: [],
    cues: ['Resist leaning toward the weight.'],
    default_scheme: time(20, 20, 's', '20s/side'),
    swap_group: 'suitcase_hold',
  },
  {
    id: 'suitcase_hold_pack',
    name: 'Suitcase Hold',
    rune_id: 'brace',
    rank: 2,
    place_tags: ['home'],
    tools_required: ['backpack'],
    joint_blockers: [],
    cues: ['Resist leaning toward the weight.'],
    default_scheme: time(20, 20, 's', '20s/side'),
    swap_group: 'suitcase_hold',
  },
  {
    id: 'farmer_carry',
    name: 'Farmer Carry',
    rune_id: 'brace',
    rank: 3,
    place_tags: ['home', 'gym'],
    tools_required: ['dumbbells'],
    joint_blockers: [],
    cues: ['Tall posture, tight grip, even steps.'],
    default_scheme: time(30, 30, 's'),
    swap_group: 'brace',
  },

  // 5.8 Spark
  {
    id: 'march_in_place',
    name: 'March in Place',
    rune_id: 'spark',
    rank: 1,
    place_tags: ['home', 'gym'],
    tools_required: ['floor'],
    joint_blockers: [],
    cues: ['Easy rhythm, knees to hip height.'],
    default_scheme: time(45, 60, 's'),
    swap_group: 'spark',
  },
  {
    id: 'easy_walk',
    name: 'Easy Walk',
    rune_id: 'spark',
    rank: 1,
    place_tags: ['home', 'gym'],
    tools_required: ['floor'],
    joint_blockers: ['knees'],
    cues: ['Conversational pace.'],
    default_scheme: time(3, 8, 'min'),
    swap_group: 'spark',
  },
  {
    id: 'step_up',
    name: 'Step Up',
    rune_id: 'spark',
    rank: 2,
    place_tags: ['home', 'gym'],
    tools_required: ['floor'],
    joint_blockers: ['knees'],
    cues: ['Drive through the lead foot.'],
    default_scheme: reps(8, 8, '8/side'),
    swap_group: 'spark',
  },
  {
    id: 'easy_bike',
    name: 'Easy Bike',
    rune_id: 'spark',
    rank: 2,
    place_tags: ['gym'],
    tools_required: ['machines'],
    joint_blockers: [],
    cues: ['Easy spin, steady breath.'],
    default_scheme: time(5, 5, 'min'),
    swap_group: 'spark',
  },
];
